<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= htmlspecialchars($ItemName); ?></title>
    </head>
    <body>
        <div>
            Item Number: <?= htmlspecialchars($ItemID); ?><br />
            Item Name: <?= htmlspecialchars($ItemName); ?><br />
            Item Description: <?= htmlspecialchars($ItemDis); ?><br />
            Item Price: <?= htmlspecialchars($ItemPrice); ?><br />
        </div>
    </body>
</html>
